spring:
  datasource:
    url: jdbc:mysql://${MYSQL_URL}?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: ${USER_NAME}
    password: ${USER_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 420000

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect  # DB 방언을 JPA가 알아서 처리할 수 있도록
    show-sql: true  # 성능 저하를 일으키므로 운영 환경에서는 쓰지 않음
    generate-ddl: true  # 테스트 데이터 넣을 수 있음
    open-in-view: false
    hibernate:
      ddl-auto: update
      # create - 스키마를 생성한다. 스키마에 이미 존재하는 데이터는 손실된다.
      # update - 스키마를 주어진 값으로 갱신한다.
      # validate - 스키마의 유효성을 검사한다. DB에 변화가 없다.
      # created-drop - 이전에 존재한 데이터를 삭제하여 스키마를 생성한다. 또한, SessionFactory가 닫힐 때 데이터베이스 스키마를 삭제한다.
    properties:
      hibernate:
        format_sql: true  # 성능 저하를 일으키므로 운영 환경에서는 쓰지 않음